[profile.default]
src = 'contracts'
test = 'foundry/test'
out = 'artifacts/foundry'
libs = ['lib', 'node_modules']
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@account-abstraction/=node_modules/@account-abstraction/',
    'forge-std/=lib/forge-std/src/'
]
solc_version = '0.8.23'
optimizer = true
optimizer_runs = 200

[fuzz]
runs = 1000
max_test_rejects = 65536

[invariant]
runs = 256
depth = 15
fail_on_revert = false 
